const PUBLIC_KEY = "-----BEGIN PUBLIC KEY-----MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC+WKbB55uPdHtZXIMX3srksl9gynOSlsHTByUGgDCoMlpl6Il638NNh1yG3+j/oZsAP+gQF+RFJrnv0KxLxgb1/ocaKZUZS+QhJ8tuvtAHQBG7fTfeSCZNUVYAUB3uTka/6naNN3RrU6OoXCPVo+FYj5YB35cMjLqUAOXpxnzGEwIDAQAB-----END PUBLIC KEY-----"
// const PUBLIC_KEY = "-----BEGIN PUBLIC KEY-----MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDrWeIGo13Pv4QcvslA58/hSV72ZXdvYj+8Zl+xLpsP7JaeKbjKuHZnmRQhIDr4Y2edMM8f1/3+we8aenHc3Rn2VkZ01QOeBOdB/ZPmjlWRdL9rfPSIfjxn5DPY6CEa0tJ0FPFYwcA7QsEyLj4l/pg5jRrctyD+oI+9Osaaq+5HRwIDAQAB-----END PUBLIC KEY-----"
module.exports = {
  PUBLIC_KEY: PUBLIC_KEY
}